version: '3.6'

volumes:
  sf4-mysql:
  sf4-app-sync:
    external: true

services:
  database:
    container_name: sf4-mysql
    restart: always
    image: mysql
    volumes:
      - sf4-mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    tty: true
    stdin_open: true

  phpfpm:
    container_name: sf4-phpfpm
    restart: always
    image: php:fpm
    volumes:
      - sf4-app-sync:${APP_PATH}:nocopy
    env_file:
      - '.env'
    tty: true
    stdin_open: true

  webserver:
    container_name: sf4-apache
    restart: always
    image: httpd
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - sf4-app-sync:${APP_PATH}:nocopy
    environment:
      - PHPFPM=sf4-phpfpm
    env_file:
      - '.env'
    tty: true
    stdin_open: true
